OpenXT/manager

xenmgr/XenMgr/Expose/XenmgrObject.hs

Add a property to control this setting:
- namespace = com.citrix.xenclient.xenmgr.config.ui
- property name = modify-usb-settings
- property type = boolean
- default = true
OXT-115
Signed-off-by: Chris Patterson <pattersonc@ainfosec.com>

manager: add getter/setter for modify-usb-settings

---

templates/default/new-vm-linux

Get rid of the CPUID that allowed the xc-xen platform
device to load.
OXT-231

Rebase PV Linux driver on standard PVOPS kernel/xenbus.

---

xenmgr/XenMgr/Expose/HostObject.hs

New audio code
Long description:
Changes the path from amixer to audio_helper as the amixer patch has
been removed
Bugs:
OXT-194: Audio Capture Setting not working
Singed-off-by: Rian Quinn <quinnr@ainfosec.com>

Short description:

---

upgrade-db/Migrations.hs
upgrade-db/Migrations/M_24.hs
upgrade-db/Migrations/M_25.hs
upgrade-db/Upgrade.hs

24->25: AC97 is now the desired setting for windows guests with latest
openxt tools.
25->26: Update ndvm kernel command line parameters to match the current
ndvm template configuration: "root=/dev/xvda1 iommu=soft xencons=hvc0"
OXT-273
OXT-274
Signed-off-by: Chris Patterson <pattersonc@ainfosec.com>

upgrade-db: add migrations 24->25 and 25->26 to match current configs

---

xenmgr/Vm/PciDatabase.hs

See https://github.com/OpenXT/xenclient-oe/pull/88
Singed-off-by: Jed Lejosne <lejosnej@ainfosec.com>

Use uncompressed version of pci.ids

---

xenmgr/Vm/Actions.hs

For AMD cards to function properly, they must support bus level reset.
Bus level reset requires all functions to be passed to the guest, so
at VM boot time, check for GPU passthrough and ensure extra functions
are also passed through.
OXT-276

If VM has multifunction gpu passthrough, pass all functions on device.

---

xenmgr/Vm/Actions.hs

Vm/Actions.hs
* Use mapM_ to force evaluation of all Rpc monadic computations
to make sure we add every function/device that matches.
* Additionally ensure we filter out the video function of gpu to
avoid passing it through twice.
OXT-296

Implement proper monadic evaluation and filtering with mapM_

---

xenmgr/XenMgr/Config.hs
xenmgr/XenMgr/Expose/XenmgrObject.hs

the input server to respond to CTRL+ALT+R when UI is focused.
OXT-335
Signed-off-by: Chris Patterson <pattersonc@ainfosec.com>

xenmgr: add switcher-status-report-enabled property to configure

---

upgrade-db/Migrations.hs
upgrade-db/Migrations/M_26.hs
upgrade-db/Upgrade.hs

This adds the default policy bits for the new USB daemon.
See related pull request in xenclient-oe.git:
https://github.com/OpenXT/xenclient-oe/pull/146

upgrade-db: add migration for the new USB policy

---

templates/default/new-vm
templates/default/new-vm-linux
templates/default/new-vm-windows8
templates/default/new-vm-xp

Now that the win-tools are gone that used these ports, they can be closed
down.
OXT-563

[v4v] Remove domU access ports to dom0

---

xenmgr/XenMgr/Host.hs

xenops (CAML toosltack) provides access to xc_physinfo without the need
for a standalone binary, so use that instead of hvm-info.
OXT-586

Replace hvm-info with xenops physinfo instead.

---

updatemgr/UpdateMgr/Logic.hs

Use the forground step to download the meta files and the background
step to do the main download. This also fixes some oddities with the UI.
OXT-734

[ota] Don't download tarballs twice.

---

updatemgr/UpdateMgr/Logic.hs

Use the forground step to download the meta files and the background
step to do the main download. This also fixes some oddities with the UI.
OXT-734

[ota] STABLE-6 Don't download tarballs twice.

---

xenmgr/Vm/Config.hs

Remove unused bios-strings values from configs and xenstore.

---

xenmgr/XenMgr/PowerManagement.hs
xenmgr/XenMgr/PowerManagement.hs-boot

the use of a bad action and then do nothing.

Add ActionInvalid PMAction type designed to log

---

xenmgr/Vm/Config.hs

CPS was disabled during early libxl testing, and without it,
OS's such as Windows 7 that limit the number of sockets prevent
us from using more than 2 vcpus at a time.
OXT-435

[libxl] Reenable cores per socket

---

xenmgr/Vm/Config.hs

If a domain disables cdrom access, the "-drive" entry is still
placed in the device_model_params, which, by itself, fails to
parse in qemu causing the domain to fail to boot.
OXT-435

[libxl] Fix bug with cdrom access

---

xenmgr/XenMgr/PowerManagement.hs
xenmgr/XenMgr/PowerManagement.hs-boot

the use of a bad action and then do nothing.
OXT-866
(cherry picked from commit e573818be505bc37cef49c67b9f9782e406f930c)

STABLE-6: Add ActionInvalid PMAction type designed to log

---

xenmgr/XenMgr/Connect/Xl.hs

stderr from libxl. For domain creation, we now capture stderr from
libxl and return it directly to the caller, as it might fail for
a variety of reasons. Other toolstack calls that fail are more
predictable and can simply provide a short error message to
the caller.
OXT-991

[libxl] Use special exception class and capture

---

xenmgr/Vm/React.hs

If there's no state node, don't fire a shutdown

---

xenmgr/Vm/Actions.hs
xenmgr/XenMgr/Expose/VmDiskObject.hs

When disabling disk persistence for a domain with an encrypted
disk, use an encrypted snapshot.
OXT-966

[xenmgr] Support encrypted snapshots

---

xenmgr/Vm/Utility.hs

In certain cases, this function would fail, throwing an exception
and crashing the domain monitoring thread.
OXT-1011

[xenmgr] Fix bug with read

---

dbd/Makefile
dbd/db_methods.ml

Makefile updated with new (as of 2011) library names.
db_methods.ml : Xs -> Xenstore.Xs
Signed-off-by: Christopher Clark <christopher.clark6@baesystems.com>

OXT-1067: Unfork: Use upstream Xen OCaml libraries

---

xenmgr/Vm/Actions.hs
xenmgr/Vm/Dm.hs
xenmgr/Vm/DmTypes.hs
xenmgr/Vm/State.hs
xenmgr/XenMgr/Connect/NetworkDaemon.hs
xenmgr/XenMgr/Connect/Xl.hs
xenmgr/XenMgr/PowerManagement.hs

Fix a few bugs along this control path in addition to new logic
for applyVmBackendShift. When ndvm_x reboots, forall frontends
with ndvm_x as a backend, cleanup all existing frontend nics and
call into networkdaemon to hookup new vifs for ndvm_x.
OXT-1011

[xenmgr] Reconnect vifs on ndvm reboot

---

upgrade-db/Migrations.hs
upgrade-db/Migrations/M_35.hs
upgrade-db/Upgrade.hs
upgrade-db/UpgradeEngine.hs
upgrade-db/upgrade-db.cabal

OXT-923 was addressed by causing nm-applet only store PSK passwords in hashed form, but any plaintext passwords in the dom-store will remain when OpenXT is upgraded. This PR adds a migration to hash all PSK passwords in the dom-store.
I used migration number 35 since the pending xl migration is using 34 (which I believe will also cause a conflict when merged).

Migration to hash WPA-PSK passwords

---

xenmgr/Vm/Queries.hs

80M has been observed as too low to allow a guest VM to reboot.
OXT-1203 for Xen upgrade.
Signed-off-by: Christopher Clark <christopher.clark6@baesystems.com>

[Xen 4.9] Increase stubdom memory from 80M to 96M

---

xenmgr/Vm/Actions.hs
xenmgr/XenMgr/Expose/VmDiskObject.hs

The option isn't implemented well enough, just key off whether
the encryption key is set or not to make an encrypted snapshot.
OXT-966

[xenmgr] Don't use temporary-encrypted

---

xenmgr/Vm/Actions.hs
xenmgr/XenMgr/Expose/VmDiskObject.hs

The option isn't implemented well enough, just key off whether
the encryption key is set or not to make an encrypted snapshot.
OXT-966

STABLE-7: [xenmgr] Don't use temporary-encrypted

---

xenmgr/Vm/Utility.hs

so use it to destroy the tap devices created during pv kernel
extraction.
OXT-1207

[xenmgr] tap-ctl destroy supports d flag again

---

xenmgr/Vm/Utility.hs

so use it to destroy the tap devices created during pv kernel
extraction.
OXT-1207

STABLE-7: [xenmgr] tap-ctl destroy supports d flag again

---

xenmgr/Vm/Actions.hs
xenmgr/XenMgr/Connect/Xl.hs
xenmgr/XenMgr/Diskmgr.hs

xenmgr: use readProcessOrDie to avoid fd leaks

---

xenmgr/Vm/Actions.hs
xenmgr/XenMgr/Connect/Xl.hs
xenmgr/XenMgr/Diskmgr.hs

OXT-1193
(cherry picked from commit fe9768d33749c15c551ed4e0ee71c990e9aa8631)

STABLE-7: xenmgr: use readProcessOrDie to avoid fd leaks

---

xenmgr/Vm/Config.hs

passthrough-mmio and passthrough-io map to iomem and ioports
in xl.  Hook up the logic in Config.hs to dump them into the config
OXT-1220

[xenmgr] Hook up passthrough-mmio/io for xl

---

xenmgr/Vm/Config.hs

passthrough-mmio and passthrough-io map to iomem and ioports
in xl.  Hook up the logic in Config.hs to dump them into the config
OXT-1220

STABLE-7: [xenmgr] Hook up passthrough-mmio/io for xl

---

upgrade-db/Migrations.hs
upgrade-db/Migrations/M_36.hs
upgrade-db/Upgrade.hs
xenmgr/Vm/Pci.hs
xenmgr/Vm/PciDatabase.hs
xenmgr/XenMgr/Config.hs

- Use Zlib already available in DEPENDS instead of relying on a forked shell to read a static database;
- Add migration script to handle changes in `openssh` configuration.
See https://github.com/OpenXT/xenclient-oe/pull/830

OXT-880: OE upgrade to pyro

---

xenmgr/Vm/React.hs

OXT-1243
(cherry picked from commit a7eeaf358a6b85934b50d9bb5cf42703d9002908)

STABLE-8: xenmgr: remove snapshot disk key on shutdown

---

xenmgr/XenMgr/Connect/Xl.hs

With suspend and resume, xec-vm fails with the error:
unable to retrieve domain configuration
Supplying the extra command parameter (the domain's xen config file)
to the underlying xl command fixes the issue.
Signed-off-by: Jafar Al-Gharaibeh <jafar@atcorp.com>

xec-vm: fix suspend/resume to/from file

---

templates/default/new-vm-sync
upgrade-db/Migrations.hs
upgrade-db/Migrations/M_38.hs
upgrade-db/Upgrade.hs

The current syncvm template creates an un-bootable config. The old template passed the flask label directly to xenm through extra-xenvm "flask-label". This worked for the xenvm-based system, but it broke with the XL conversion. "flask-label" is invalid in the XL config ("seclabel" should be used), so it throws an error about the legacy Python syntax.
The migration code hardcodes the syncvm_t flask label.  Alternate labels will be clobbered, but this doesn't seem like a realistic case to handle.

OXT-1384: Syncvm Flask label

---

templates/default/new-vm-sync
upgrade-db/Migrations.hs
upgrade-db/Migrations/M_37.hs
upgrade-db/Migrations/M_38.hs
upgrade-db/Upgrade.hs

This is the stable-8 version of https://github.com/OpenXT/manager/pull/123
The current syncvm template creates an un-bootable config. The old template passed the flask label directly to xenvm through extra-xenvm "flask-label". This worked for the xenvm-based system, but it broke with the XL conversion. "flask-label" is invalid in the XL config ("seclabel" should be used), so it throws an error about the legacy Python syntax.
The migration code hardcodes the syncvm_t flask label. Alternate labels will be clobbered, but this doesn't seem like a realistic case to handle.
This stable-8 version skips db version 38.  Migrations/M_37.hs is a placeholder empty file.  In the log output you see `update-db: Migrating 37 -> 39` skipping the intermediate version.

STABLE-8: OXT-1384: Syncvm Flask label

---

xenmgr/Vm/Actions.hs
xenmgr/Vm/Config.hs
xenmgr/Vm/Queries.hs
xenmgr/XenMgr/Expose/VmObject.hs

BIOS option allows a user to choose between a guest using UEFI through OVMF, or traditional BIOS through SeaBios

OXT-1431: Guest UEFI support

---

xenmgr/Vm/Config.hs

time-offset is not a valid XL option - XL thinks it is python.  A
similar XL option is rtc_timeoffset which sets the real time clock
offset in seconds.  I don't know what the old units were for this option
though.  xenvm did not seem to do anything with the value.
OXT-1442

OXT-1442: xenmgr: Use xl option rtc_timeoffset

---

xenmgr/XenMgr/Host.hs

dmidecode may return more than one type, e.g:
```sh
root@e7470:~# dmidecode -s chassis-type
Laptop
Docking Station
```
A docked laptop is still a laptop.
Use a list of keywords and check every line for a match.

OXT-796: xenmgr: Match multi-strings in dmi chassis type.

---

xenmgr/XenMgr/Host.hs

dmidecode may return more than one type, e.g:
root@e7470:~# dmidecode -s chassis-type
Laptop
Docking Station
A docked laptop is still a laptop.
Use a list of keywords and check every line for a match.
(cherry picked from commit 6a756b405a3b18813752d9150deafe7ca3997f0e)

STABLE-8: OXT-796: xenmgr: Match multi-strings in dmi chassis type.

---

xenmgr/Vm/Config.hs

OXT-1556
For cdrom devices keep the name as 'hdc' because this is
used in iso-hotswap code.
AHCI currently doesn't support read-only devices, hence cdrom devices
cannot be AHCI emulated.
Signed-off-by: Mahantesh Salimath <salimathm@ainfosec.com>

OXT-1556: fix iso-hotswap

---

xenmgr/Vm/Config.hs

OXT-1556
For cdrom devices keep the name as 'hdc' because this is
used in iso-hotswap code.
AHCI currently doesn't support read-only devices, hence cdrom devices
cannot be AHCI emulated.
Signed-off-by: Mahantesh Salimath <salimathm@ainfosec.com>

STABLE-9: OXT-1556: fix iso-hotswap

---

xenmgr/XenMgr/Connect/Xl.hs

"active vms" isn't informative.  Add the uuid to the output.

xenmgr: Print the uuid during state checks

---

xenmgr/XenMgr/Connect/Xl.hs

Stable-9 version of https://github.com/OpenXT/manager/pull/142
"active vms" isn't informative.  Add the uuid to the output.
(cherry picked from commit 7341f9040818c705fa2abdfcf316dd723198f597)

STABLE-9: xenmgr: Print the uuid during state checks

---

rpc-proxy/Firewall.hs
rpc-proxy/Msg/DBus.hs
rpc-proxy/Msg/Json.hs
rpc-proxy/RpcProxy.hs

This PR changes lots of messages to debug priority which makes rpc-proxy less chatty in /var/log/messages.  They are at debug level, so rsyslog sees them and then chooses to ignore them with out default /etc/rsyslog.conf.
For a single message, it changes from
> rpc-proxy: incoming connection from domain 1, port 0x9e366f5e, fd is 10
> rpc-proxy: null byte received from incoming transport - setting up conversation
> rpc-proxy: authenticating client <v4v: 10> ArtefactSource {sourceDomainID = 1, sourceUuid = Just 00000000-0000-0000-0000-000000000002, sourceIsStubdom = False} rpc-proxy: auth: null byte sent to server
> rpc-proxy: auth done for <v4v: 10>
> rpc-proxy: starting forwarding <socket: 14> -> <v4v: 10>
> rpc-proxy: starting forwarding <v4v: 10> -> <socket: 14>
> rpc-proxy: assuming …

Quiet rpc-proxy

---

rpc-proxy/Firewall.hs
rpc-proxy/Msg/DBus.hs
rpc-proxy/Msg/Json.hs
rpc-proxy/RpcProxy.hs

Stable-9 version of https://github.com/OpenXT/manager/pull/143
This PR changes lots of messages to debug priority which makes rpc-proxy less chatty in /var/log/messages. They are at debug level, so rsyslog sees them and then chooses to ignore them with out default /etc/rsyslog.conf.
For a single message, it changes from
> rpc-proxy: incoming connection from domain 1, port 0x9e366f5e, fd is 10
> rpc-proxy: null byte received from incoming transport - setting up conversation
> rpc-proxy: authenticating client <v4v: 10> ArtefactSource {sourceDomainID = 1, sourceUuid = Just 00000000-0000-0000-0000-000000000002, sourceIsStubdom = False} rpc-proxy: auth: null byte sent to server
> rpc-proxy: auth done for <v4v: 10>
> rpc-proxy: starting forwarding <socket: 14> -> <v4v: 10>
> rpc-proxy: starting …

STABLE-9: Quiet rpc-proxy

---

xenmgr/Vm/Dm.hs

We have domains providing network backends that do not run
network-slave.  In those cases, when the VM restarts, network-daemon
repeatedly tries to call network-slave resulting in eventual failure.
network-daemon: domain's 12 sytem bus is unresponsive: connect: invalid argument (Transport endpoint is not connected), retrying..
If we don't specify a "network" in the nic config, xenmgr won't try to
reconnect frontends.  Change that to instead call Xl.setNicBackendDom
when network is empty and bypass talking to network daemon/slave.  That
way we'll reconnect and avoid syslog messages.

xenmgr: Reconnect VIFs manually

---

xenmgr/XenMgr/Connect/Xl.hs

The QEMU ACPI hvm-shutdown and hvm-power-button xenstore entries don't
always work.  On the QEMU side, it looks like the IRQ is raised and the
ACPI_SLP_BIT is cleared, but the guest doesn't shutdown.  `xl shutdown
-F -w` just hangs.
Manually running `xl trigger DomU power` after that seems to trigger the
shutdown, so just have xenmgr make that invocation.

xenmgr: Add xl trigger power to HVM shutdown

---

xenmgr/Vm/Dm.hs

Stable-9 version of https://github.com/OpenXT/manager/pull/141
We have domains providing network backends that do not run
network-slave.  In those cases, when the VM restarts, network-daemon
repeatedly tries to call network-slave resulting in eventual failure.
network-daemon: domain's 12 sytem bus is unresponsive: connect: invalid argument (Transport endpoint is not connected), retrying..
If we don't specify a "network" in the nic config, xenmgr won't try to
reconnect frontends.  Change that to instead call Xl.setNicBackendDom
when network is empty and bypass talking to network daemon/slave.  That
way we'll reconnect and avoid syslog message.
(cherry picked from commit 7779984634616e93d486ceb2674ef64cd74206d1)

STABLE-9: xenmgr: Reconnect VIFs manually

---

xenmgr/Vm/React.hs

/dev/xvc0 doesn't exist on para-virt Xen kernels.  Use /dev/hvc0 to
actually print out the message.

xenmgr: Use /dev/hvc0 for measurement failure messages

---

xenmgr/Vm/React.hs

When a VM was set for "Power control affects VM and host", I was seeing
a guest reboot end up shutting down the host.  When "shutdown vm" is
called, the shutdown reason reason was observed to be Halt or Reboot - I
haven't seen Restarting.  Check for Halt and shutdown the host in that
case.  That could miss the AcpiPowerOff reason, but that has not been
seen in practice.
@crogers1 you set this to the original 'reason /= Restarting'.  Is there something I am missing?
'data ShutdownReason = CreationFailure | Reboot | Hibernate | Halt | Restarting | AcpiPoweroff'
To be clear, in older versions a guest initiated reboot did not affect the host power state - only the guest rebooted.

xenmgr: Fix Power control affects VM and Host

---

xenmgr/Vm/React.hs

This is the Stable-9 version of https://github.com/OpenXT/manager/pull/152
When a VM was set for "Power control affects VM and host", I was seeing
a guest reboot end up shutting down the host.  When "shutdown vm" is
called, the shutdown reason reason was observed to be Halt or Reboot - I
haven't seen Restarting.  Check for Halt and shutdown the host in that
case.  That could miss the AcpiPowerOff reason, but that has not been
seen in practice.
(cherry picked from commit 20c7e134857ec71a68009c2575f2f8cbe67f2847)

S9: xenmgr: Fix Power control affects VM and Host

---

xenmgr/Vm/React.hs

This is the stable-9 version of https://github.com/OpenXT/manager/pull/153
/dev/xvc0 doesn't exist on para-virt Xen kernels.  Use /dev/hvc0 to
actually print out the message.
(cherry picked from commit b3788aa4e5a6e09b91d96e3bc8935f722a96ab66)

S9: xenmgr: Use /dev/hvc0 for measurement failure messages

---

xenmgr/Vm/Actions.hs

runInteractiveProcess doesn't touch FDs, so it leaks them out into the
wild.  This is seen by AVCs for /etc/xenclient.conf and a socket or pipe
when a shell script runs.
Switch to createProcess so we can set close_fds = True and avoid the
leakage.

xenmgr: avoid leaking FDs to run scripts

---

xenmgr/Vm/Actions.hs

This is the stable-9 version of https://github.com/OpenXT/manager/pull/155
runInteractiveProcess doesn't touch FDs, so it leaks them out into the
wild.  This is seen by AVCs for /etc/xenclient.conf and a socket or pipe
when a shell script runs.
Switch to createProcess so we can set close_fds = True and avoid the
leakage.
(cherry picked from commit 1a04967c637c65d996ab7d80dbeae304a5872bc0)

S9: xenmgr: avoid leaking FDs to run scripts

---

xenmgr/XenMgr/Connect/Xl.hs

This is the Stable-9 version of https://github.com/OpenXT/manager/pull/150
The QEMU ACPI hvm-shutdown and hvm-power-button xenstore entries don't
always work.  On the QEMU side, it looks like the IRQ is raised and the
ACPI_SLP_BIT is cleared, but the guest doesn't shutdown.  `xl shutdown
-F -w` just hangs.
Manually running `xl trigger DomU power` after that seems to trigger the
shutdown, so just have xenmgr make that invocation.
(cherry picked from commit 1cfb6aa8e63e45f09b36690bca09128bebad465a)

S9: xenmgr: Add xl trigger power to HVM shutdown

---

xenmgr/XenMgr/Connect/Xl.hs

This is the stable-9 version of https://github.com/OpenXT/manager/pull/159
xl create lives for the lifetime of the domain, so we don't want it to
have our FDs.  The other commands are one-offs, but they don't need to
inherit FDs.
These commands remain in the same SELinux domain (type), so they don't
cause avcs.
(cherry picked from commit b09ad99476cb232f026c95b2be738ac574ccb728)

S9: xenmgr: Close some FD leaks

---

templates/default/new-vm-linux

For Linux guests, with AHCI emulation there will be 2 disks
shown to the guest; the AHCI emulated and the PV blkfront which
is compiled into most modern Linux distros. Have Linux guests
use IDE emulation so the Xen/Qemu unplug path can remove the
emulated disk to avoid confusing the user. AHCI vs IDE doesn't
matter because the PV driver will be used anyway.
OXT-1582

OXT-1582: [linux] Use ide instead of AHCI

---

templates/default/new-vm-linux

For Linux guests, with AHCI emulation there will be 2 disks
shown to the guest; the AHCI emulated and the PV blkfront which
is compiled into most modern Linux distros. Have Linux guests
use IDE emulation so the Xen/Qemu unplug path can remove the
emulated disk to avoid confusing the user. AHCI vs IDE doesn't
matter because the PV driver will be used anyway.
OXT-1582
(cherry picked from commit 159a874bcaa46f15246e5ea30ddbfd354a050da5)

STABLE-9: OXT-1582: [linux] Use ide instead of AHCI

---

templates/default/service-uivm

Change `virt-type` from `pv` to `pvh`.

OXT-1647: templates: Make UIVM default to PVH.

---

templates/default/service-uivm

Change `virt-type` from `pv` to `pvh`.

S9: OXT-1647: templates: Make UIVM default to PVH.

---

templates/default/new-vm-sync
templates/default/service-uivm

xencons is the old option name which has no affect on modern linux.  Use
console to specify the console.
This will restore console output in /var/log/messages from uivm and
syncvm.

templates: Switch xencons to console

---

upgrade-db/Upgrade.hs

Upgrades are not handling the v4v->argo conversion since Migration_40 is
not being run.  We need to set latestVersion to 41 to run the
migrations.
NDVM & UIVM don't have a problem since their configs are injected from
on-disk copies already updated for argo at boot time.  It's only other
existing VMs with v4v rules that need updating.

OXT-1684: upgrade-db: Update db-version to apply Migration_40

---

upgrade-db/Upgrade.hs

Stable-9 version of https://github.com/OpenXT/manager/pull/173
Upgrades are not handling the v4v->argo conversion since Migration_40 is
not being run.  We need to set latestVersion to 41 to run the
migrations.
NDVM & UIVM don't have a problem since their configs are injected from
on-disk copies already updated for argo at boot time.  It's only other
existing VMs with v4v rules that need updating.
(cherry picked from commit 551206c0da0ba6adc03356005cecfc1a2c7442ba)

S9: OXT-1684: upgrade-db: Update db-version to apply Migration_40

---

templates/default/new-vm
templates/default/new-vm-linux
templates/default/new-vm-windows8
templates/default/new-vm-xp

Since Argo is primarily used by service VMs, it is disabled by XSM
for guest VMs.  When enabled in the VM config file, Argo causes an
unknown device to appear in Windows Device Manager.  Disable argo in
VM config, to avoid alarming guest monitoring agents.
OXT-1752
Signed-off-by: Rich Persaud <rich.persaud@baesystems.com>

OXT-1752 : templates: disable Argo for user VMs

---

dbd/Makefile
dbd/Makefile.rules

ocamlfind is a frontend with the package manager.
dbd uses it to find the necessary options to pass to ocamlc/ocamlopt in
order to use the packages managed by findlib (ocamlfind
<ocamlc|ocamlopt> -package).  This is done by overriding the
OCAMLC/OCAMLOPT variables that are already used by ocaml.bbclass to pass
the cross environment options.
In order to avoid re-writing more build-system bits, use ocamlfind for
every library to invoke the byte-code and native compiler and pass
additional package (-linkpkg/-package) options through OCAMLCOPT and
OCAMLOPTOPT. This way OCAMLC and OCAMLOPT can define the specific cross
environment and ocamlfind can provide its services to include packages
through findlib.

S9: OXT-1787: ocamlfind: use across the board for libraries

---

apptool/samples/uivm.ovf
templates/default/new-vm
templates/default/new-vm-linux
templates/default/new-vm-windows8
templates/default/new-vm-xp
templates/default/service-uivm
xenmgr/Main.hs
xenmgr/Vm/Actions.hs
xenmgr/Vm/Config.hs
xenmgr/Vm/Pci.hs
xenmgr/Vm/Queries.hs
xenmgr/Vm/Queries.hs-boot
xenmgr/Vm/React.hs
xenmgr/Vm/Types.hs
xenmgr/XenMgr/Config.hs
xenmgr/XenMgr/Connect/Xl.hs
xenmgr/XenMgr/Errors.hs
xenmgr/XenMgr/Expose/HostObject.hs
xenmgr/XenMgr/Expose/VmObject.hs
xenmgr/XenMgr/Expose/XenmgrObject.hs
xenmgr/XenMgr/Host.hs
xenmgr/XenMgr/Notify.hs
xenmgr/XenMgr/PowerManagement.hs
xenmgr/xenmgr.cabal

This changeset has 3 steps:
- Remove Surfman's integration and rules hardwired in the toolstack;
- Add vglass RPC and required logic to enable the vglass graphic stack;
- Enable vglass as the default graphic stack.
vglass support is enabled through the `vglass-enabled` configuration property, which is enabled by default for new guests and UIVM.
NOTE: PV and PVH guests that rely on openxtfb or glassdrm (e.g, UIVM) may experience a 30s boot time delay as xenbus will wait for the PV framebuffer/input devices to be connected to their backends. This is why `xenbus.wait_nonessentials` is provided and introduced by a Linux path in xenclient-oe.
NOTE: At the moment, emulated pointing devices do not work if PV tools are installed in Windows guests, this is why the configuration property `vkbd` is …

vglass: deprecate surfman logics and wire up vglass

---

templates/default/new-vm-sync

Default syncvm to running as a PVH with HAP, hardware assisted paging,
enabled.  PVH and HAP avoid spectre & meltdown security issues associated
with PV.
Depends on https://github.com/OpenXT/xenclient-oe/pull/1420 and https://github.com/OpenXT/xsm-policy/pull/38

templates: Make sync pvh and hap

---

xenmgr/XenMgr/Connect/Xl.hs

These can get excessive filling /var/log/messages.  It's unclear exactly
why, but make them debug so we don't see them.

xenmgr: Demote "active vm" messages to debug

---

xenmgr/XenMgr/Config.hs

Trying to disable dom0 networking by setting xenmgr.config propery enable-dom0-networking to False fails with:
223:IO error: /config/system/dom0-networking-disabled: openFile: does not exist (No such file or directory)
/config/system does not exist.  Ensure we create it if needed.

xenmgr: Fix enable-dom0-networking

---

xenmgr/XenMgr/Connect/Xl.hs

Calling xl commands via system leaks FDs.  Add a new helper system_ with
that same prototype that closes FDs under the hood.

xenmgr: Don't leak FDs with xl commands

---

xenmgr/XenMgr/Expose/HostObject.hs
xenmgr/XenMgr/HostOps.hs
xenmgr/XenMgr/PowerManagement.hs
xenmgr/XenMgr/PowerManagement.hs-boot

Implement a separate function for handling the idle shutdown
case. When the system has been idle for the specified idle period
and no user input has been detected, shutdown the platform. Start
a 5 minute timer that will force the host off if has not completed
the shutdown process.
If the idle timer feature is enabled, then the expected behavior is
that the host will be shutdown. This commit ensures that the host will
reach the off state in the event of a stuck guest VM or otherwise non-
responding process when handling an idle shutdown within a reasonable
amount of time.

[xenmgr] Add idle shutdown specific call

---

dbd/dbd.ml

dbd is a mostly idle daemon, but is wakes up every second.  Bump up the
sleep times to be idle longer.
There is already logic to write out a dirty tree at least every 3 seconds.
Therefore, the new logic sets a 3 second sleep as the minimum for use
when the tree is dirty.  If the tree is clean (either unchanged, or we
just flushed it), then we sleep indefinitely.  This should nicely remove
extraneous wakeups.
The existing time code tracks the last write.  When dbd has been idle
for 3 seconds, the next write is flushed immediate.  Subsequent writes
for the next 3 seconds queued up and are then flushed.  This does not
change with the patch.

dbd: Sleep longer

---

dbd/db_core.ml
dbd/db_methods.ml
dbd/dbd.ml

dbd write logging is questionable.  The logging of the large dbd writes by varstored makes it undesirable.  The first patch lowers the write logging to syslog debug level, as well as "Updating database" mesages.  The second adds a `--debug` flag to stop generating the messages.
Complements guest UEFI https://github.com/OpenXT/xenclient-oe/pull/1434

dbd: Quiet debug logging

---

xenmgr/Vm/Actions.hs

doVmFirewallRules prints vms for both before and after.  The after should be vms' to actually show the difference.
While doing this, align the text for easier comparison in the logs.
Clean up surrounding trailing whitespace while touching this.

xenmgr: Fix printing vms on Firewall change

---

templates/default/service-ndvm-hvm
templates/default/service-usbvm
xenmgr/Vm/Templates.hs

This adds a key to toggle usbvm on.  If you toggle on and then off, the usbvm actually remains in dbd and requires manual removal.
It also adds a template for usbvm and the use of dm_ndvm_t typealias from xsm-policy PR https://github.com/OpenXT/xsm-policy/pull/39

usbvm support

---

xenmgr/XenMgr/Connect/Xl.hs

Sometimes the shutdown command does not work.  It seems like the longer the VM is up, the more likely it is to not shutdown.  This is based on Windows 10 without PV drivers.
The button press is seen by the VM to some extent because a DPMS off (black) screen will turn on, but shutdown is not initiated.  A second press will trigger it - that was the intent to the xl trigger power line added in commit 1cfb6aa8e63e "xenmgr: Add xl trigger power to HVM shutdown".
Re-work the code so a background thread is started that will push the power buttons* 3 times each with a 1 second delay.  This will hopefully let the VM recognize the button press without going on for too long.
*HVMs have two power and two sleep buttons.  One is Xen emulating buttons for HVMs, and the second is from QEMU's …

xenmgr: Push ACPI power button multiple times

---

templates/default/new-vm-ndvm-hvm
templates/default/new-vm-ndvm-pv
templates/default/service-ndvm-hvm
templates/default/service-ndvm-pv

Since commit 5d1bcbac43ee "xenmgr: Avoid generating invalid configs" a unified config can be used and switched by just flipping virt-type. Bring the two configs together so they just differ by virt-type.

templates: sync ndvm-pv and ndvm-hvm
