xenmgr/Vm/React.hs
OXT-191
Singed-off-by: Jed Lejosne <jed.openxt@gmail.com>
=> fix per-VM alsa config path

templates/default/new-vm, templates/default/new-vm-windows8
Replace Ioemu with QEMU 1.4 in OpenXT
https://openxt.atlassian.net/browse/OXT-118
https://groups.google.com/forum/#!topic/openxt/FX4sbWt6soI
=> [OXT-118] Replace Ioemu with QEMU 1.4 in OpenXT

xenmgr/XenMgr/Host.hs
XenMgr/Host.hs
* Locate integrated graphics (surfman gpu) by parsing pci devices
and matching on gpu that has boot_vga set.  Then update HostGpu
so xenmgr is aware of the surfman gpu.
=> Properly set HostGpu for surfman gpu

templates/default/service-uivm
Edited service-uivm template to permit xcpmd messages to support
conversion from UPower to xcpmd in the UI
=> Added rpc-firewall-rule for permitting xcpmd

templates/default/service-ndvm, templates/default/service-uivm
=> VM templates: un-duplicate

templates/default/new-vm-ndvm, templates/default/service-ndvm, templates/default/service-uivm
=> templates: avoid wildcard firewall rules to dom0

upgrade-db/Migrations/M_26.hs
=> Deny mouse passthrough by default

xenmgr/Main.hs
=> xenmgr: remove unused string

upgrade-db/Migrations.hs, upgrade-db/Migrations/M_29.hs, upgrade-db/Upgrade.hs
=> Add migration script to disable cdrom autolock

templates/default/new-vm, templates/default/new-vm-linux, templates/default/new-vm-windows8, templates/default/new-vm-xp, xenmgr/Vm/Queries.hs
=> Handle the default stubdom memory and cmdline outside of the VM configs

templates/default/new-vm, templates/default/new-vm-linux, templates/default/new-vm-windows8, templates/default/new-vm-xp, xenmgr/Vm/Queries.hs
OXT-730
(cherry picked from commit 872aea5756ea60e7d0a2abdc31687de3ac5b0777)
=> STABLE-6: Handle the default stubdom memory and cmdline outside of the VM configs

templates/default/new-vm, templates/default/new-vm-linux, templates/default/new-vm-windows8, templates/default/new-vm-xp, xenmgr/Vm/Queries.hs
=> STABLE-5: Handle the default stubdom memory and cmdline outside of the VM configs

upgrade-db/Migrations.hs, upgrade-db/Migrations/M_30.hs, upgrade-db/Upgrade.hs
OXT-582
(cherry picked from commit 9cfb086298ce56466cd4baf5807e95ca7ef22bea)
=> STABLE-6 Move the USB mouse rule to a new migration script

upgrade-db/Migrations.hs, upgrade-db/Migrations/M_30.hs, upgrade-db/Upgrade.hs
=> Move the USB mouse rule to a new migration script

upgrade-db/Migrations.hs, upgrade-db/Migrations/M_31.hs, upgrade-db/Upgrade.hs
(cherry picked from commit 4be66ab1e066f0915d1842e00639bfcd79ccd551)
=> STABLE-6: Add migration script to fix the guest v4v firewall rules

upgrade-db/Migrations.hs, upgrade-db/Migrations/M_31.hs, upgrade-db/Upgrade.hs
=> Add migration script to fix the guest v4v firewall rules

updatemgr/UpdateMgr/Logic.hs
Thanks to Chris Rogers for the code.
OXT-832
=> [Upgrade] Allow wildcard matching on upgradeable versions.

updatemgr/UpdateMgr/Logic.hs
Thanks to Chris Rogers for the code.
OXT-832
=> [Upgrade] STABLE-6 Allow wildcard matching on upgradeable versions.

upgrade-db/Migrations.hs, upgrade-db/Migrations/M_32.hs, upgrade-db/Migrations/M_33.hs, upgrade-db/Upgrade.hs
=> Add migration scripts to bump the memory of ndvm and syncvm

upgrade-db/Migrations.hs, upgrade-db/Migrations/M_32.hs, upgrade-db/Migrations/M_33.hs, upgrade-db/Upgrade.hs
OXT-863
(cherry picked from commit 931442304e600208c90fe47107531f9418cf50d0)
=> STABLE-6: Add migration scripts to bump the memory of ndvm and syncvm

updatemgr/UpdateMgr/Logic.hs
OXT-874
(cherry picked from commit 037a347118773a66b47cd832127b57573e10b54a)
=> STABLE-6: updatemgr: checkVersion: write end conditions

updatemgr/UpdateMgr/Logic.hs
=> updatemgr: checkVersion: write end conditions

xenmgr/XenMgr/Host.hs
=> Replace a xenops call by an xl one

xenmgr/Vm/Actions.hs, xenmgr/Vm/React.hs
Xenvm implemented the logic to create a vhd snapshot on the fly
at domain boot time if disk persistence is set to disabled.
This feature isn't something that should be implemented at that
level of the toolstack, so let's have xenmgr handle it.
OXT-435
=> [libxl] Fix disk persistence

xenmgr/Vm/Config.hs
=> Set global pci options for pci passthru

xenmgr/Vm/Pci.hs, xenmgr/XenMgr/Host.hs
=> STABLE-6: [xenmgr] Gpu pci class id masking

xenmgr/Vm/Pci.hs, xenmgr/XenMgr/Host.hs
=> [xenmgr] Gpu pci class id masking

xenmgr/Vm/Actions.hs
=> [xenmgr] On vm deletion, remove state node

xenmgr/Vm/Config.hs
=> [xenmgr] Send atapi args through xl disk spec

xenmgr/Vm/Config.hs
=> xenmgr: fix backwards atapi-pt logic

xenmgr/Vm/React.hs
=> [xenmgr] Fix path to remove snapshot on shutdown

xenmgr/Vm/Actions.hs, xenmgr/Vm/Queries.hs
=> xenmgr: remove key file along with vhd

xenmgr/Vm/React.hs
=> STABLE-7: [xenmgr] Fix path to remove snapshot on shutdown

xenmgr/Vm/Actions.hs, xenmgr/Vm/Queries.hs
OXT-909
(cherry picked from commit 53fc92a518a2e79cbc99cf242da8e5c8c65dff2e)
=> STABLE-7: xenmgr: remove key file along with vhd

xenmgr/Vm/React.hs, xenmgr/XenMgr/PowerManagement.hs
=> [xenmgr] Fix Power Control support

xenmgr/Vm/React.hs, xenmgr/XenMgr/PowerManagement.hs
=> STABLE-7: [xenmgr] Fix Power Control support

xenmgr/Vm/Config.hs, xenmgr/Vm/Pci.hs
XenVM used to adjust the MMIO hole of the guest depending on PCI
devices, and there resources, being passed-through. This behaviour is
now missing, leaving the MMIO hole too small to accomodate all the
required iomem resources below 4g.
OXT-1082
=> OXT-1082: xenmgr MMIO hole size detection.

xenmgr/Vm/Config.hs, xenmgr/Vm/Pci.hs
XenVM used to adjust the MMIO hole of the guest depending on PCI
devices, and there resources, being passed-through. This behaviour is
now missing, leaving the MMIO hole too small to accomodate all the
required iomem resources below 4g.
=> STABLE-7: OXT-1082: xenmgr MMIO hole size detection.

xenmgr/XenMgr/Connect/Xl.hs
isn't listening for acpi signals. Also write hvm-shutdown node
that qemu acpi code is watching.
OXT-1091
=> [xenmgr] Send new hard shutdown flag if guest

xenmgr/XenMgr/Connect/Xl.hs
isn't listening for acpi signals. Also write hvm-shutdown node
that qemu acpi code is watching.
OXT-1091
=> STABLE-7: Oxt 1091 stable7

upgrade-db/Migrations.hs, upgrade-db/Migrations/M_34.hs, upgrade-db/Upgrade.hs
OXT-915
OXT-1059
OXT-1088
Signed-off-by: Troy Crosley <crosleyt@ainfosec.com>
=> upgrade-db: add XL migration script

upgrade-db/Migrations.hs, upgrade-db/Migrations/M_34.hs, upgrade-db/Upgrade.hs
OXT-915
OXT-1059
OXT-1088
Signed-off-by: Troy Crosley <crosleyt@ainfosec.com>
(cherry picked from commit 002bc3bd58a3f3f9be7a2cd311a5122ee5b62d74)
=> STABLE-7: upgrade-db: add XL migration script

upgrade-db/Migrations.hs, upgrade-db/Migrations/M_35.hs, upgrade-db/Upgrade.hs, upgrade-db/UpgradeEngine.hs, upgrade-db/upgrade-db.cabal
Original PR:
- https://github.com/OpenXT/manager/pull/82
=> STABLE-7: OXT-923: migrations psk partial

xenmgr/Vm/Actions.hs, xenmgr/Vm/Config.hs, xenmgr/Vm/DmTypes.hs, xenmgr/Vm/Queries.hs, xenmgr/XenMgr/Expose/VmNicObject.hs
=> [manager] Support model type for vifs

xenmgr/Vm/Actions.hs, xenmgr/Vm/Config.hs, xenmgr/Vm/DmTypes.hs, xenmgr/Vm/Queries.hs, xenmgr/XenMgr/Expose/VmNicObject.hs
=> STABLE-7: [manager] Support model type for vifs

apptool/Import/Images.hs, xenmgr/Vm/Actions.hs, xenmgr/XenMgr/Connect/Xl.hs
=> wait for domain to shutdown

xenmgr/Vm/React.hs
OXT-1270
Signed-off-by: Mahantesh Salimath <mahantesh.openxt@gmail.com>
=> uivm reboot fix : update xenmgr state to notify xl

xenmgr/Vm/Config.hs
=> xenmgr: xl.cfg: use the qemu path VM property

xenmgr/Vm/Config.hs
(cherry picked from commit 64fc9f892309577241a77a75a7420597ece372b7)
=> STABLE-8: xenmgr: xl.cfg: use the qemu path VM property

xenmgr/Main.hs, xenmgr/Vm/Actions.hs, xenmgr/Vm/Monitor.hs, xenmgr/Vm/Queries.hs, xenmgr/Vm/React.hs, xenmgr/Vm/State.hs, xenmgr/Vm/Utility.hs, xenmgr/XenMgr/Connect/Xl.hs, xenmgr/XenMgr/Expose/VmObject.hs
=> [manager] Fixup domain reboot without sleeps

xenmgr/Main.hs, xenmgr/Vm/Actions.hs, xenmgr/Vm/Monitor.hs, xenmgr/Vm/Queries.hs, xenmgr/Vm/React.hs, xenmgr/Vm/State.hs, xenmgr/Vm/Utility.hs, xenmgr/XenMgr/Connect/Xl.hs, xenmgr/XenMgr/Expose/VmObject.hs
=> STABLE-8: Domain reboot fix

xenmgr/Vm/React.hs
=> xenmgr: remove snapshot disk key on shutdown

xenmgr/Vm/Config.hs
=> Fix XL syntax for raw disks

xenmgr/Vm/Config.hs
(cherry picked from commit d6e1121b05289180db0e06d8f629938a425aa04b)
=> STABLE-8: Fix XL syntax for raw disks

templates/default/new-vm, templates/default/new-vm-empty, templates/default/new-vm-linux, templates/default/new-vm-ndvm-hvm, templates/default/new-vm-windows8, templates/default/new-vm-xp, templates/default/service-ndvm-hvm, xenmgr/Vm/Actions.hs, xenmgr/Vm/Config.hs, xenmgr/Vm/Queries.hs, xenmgr/XenMgr/Expose/VmObject.hs
=> Add  AHCI support (Qemu SATA disk emulation)

xenmgr/Vm/Config.hs
Putting this up while I sort out some issues with my build tree, note this is untested for now. Once I get xenmgr building I will test this change out.
OXT-1287
=> [xenmgr] Add initrd to xl config

xenmgr/Vm/Actions.hs
When a the phys-path to a VM's disk is bad, the VM can be stuck
for a long time in an invalid state without a visual indication
something is wrong. This will also catch the case where a phys-path
is empty or the actual disk was deleted or moved. Xenmgr will throw
an error which can be seen in the UI and the VM state will be
reset to a sane state of Shutdown.
OXT-1596
=> OXT-1596: [xenmgr] Error if VMs disk paths are bad

xenmgr/Vm/Actions.hs
When a the phys-path to a VM's disk is bad, the VM can be stuck
for a long time in an invalid state without a visual indication
something is wrong. This will also catch the case where a phys-path
is empty or the actual disk was deleted or moved. Xenmgr will throw
an error which can be seen in the UI and the VM state will be
reset to a sane state of Shutdown.
OXT-1596
=> STABLE-9: OXT-1596: [xenmgr] Error if VMs disk paths are bad

xenmgr/XenMgr/Connect/Xl.hs
xl create lives for the lifetime of the domain, so we don't want it to
have our FDs.  The other commands are one-offs, but they don't need to
inherit FDs.
These commands remain in the same SELinux domain (type), so they don't
cause avcs.
=> xenmgr: Close some FD leaks

xenmgr/Vm/Templates.hs
=> [xenmgr] Default to hvm ndvm for x64

xenmgr/Vm/Templates.hs
(cherry picked from commit a3b832bd02e458b2945524f38e63db126c7be9a2)
=> S9: [xenmgr] Default to hvm ndvm for x64

xenmgr/XenMgr/Connect/Xl.hs
xenclient-oe commit 6dde8833f7de "xen: Remove duplicate xenstore writes"
changed a domain's control xenstore directory to read-only.  This broke
stubdom qemu's ability to write to "control/hvm-powerbutton-enable".
Without that node, xenmgr wouldn't use the acpi shutdown paths.
Switch to writing hvm-powerbutton-enable and hvm-shutdown in the
device-model directory of qemu-dm's domain.  That is either the stubdom
or dom0.  Logically it makes sense to put this device-model information
underneath the device-model instead of the guest.  It also side steps
the permission issue.
Goes along with https://github.com/OpenXT/xenclient-oe/pull/1304
=> xenmgr: Use device-model directory for shutdown

dbd/Makefile, dbd/Makefile.rules
- ocamlfind: use across the board for libraries
- Fix makefile dependency generation.
=> OXT-1787: dbd: Fix builds with findlib & parallelism

xenmgr/Vm/Utility.hs
Failure to start a PV VM with partitioned disk has been observed.
xenmgr cannot mount the disk to extract the kernek:
"IO error command "mount -o ro /dev/loop0p1 /tmp/tempdir=00000001" FAILED"
This is similar to OXT-1538, but slightly different.
It seems there is a race between udev labeling the device node and mount
mounting it.  This was hinted at by the addition to the refpolicy of a
dontaudit for mount_t on device_t (xenclient-oe commit a76ead77ddbe
"refpolicy: Silence mount AVC").  While the mount succeeded in that
case, it fails now - possibly from the dunfell uprev?
Add a call to `udevadm settle` to let udev label the loop partitions
with fixed_disk_device_t.  This is potentially still racy since udevadm
could be called while the udev queue is still empty.
Signed-off-by: Jason …
=> xenmgr: Wait for loop partition labeling

xenmgr/Vm/Config.hs
It would be nice to have ndvm be able to toggle between hvm and pv by
just flipping the virt-type, but that isn't possible today.  xenmgr
needs to be more selective to only write appropriate options into the
xl.cfg for the corresponding virt-type.  This commit attempts to do so.
Centralize and expand the virt-type specific options in virtSpecs.
HVMs in OpenXT can't be direct booted, so don't provide kernel or
cmdline in that case.  xl throws an error when they are in xl.cfg for an
HVM.
"boot" is only relevant for HVM, but PV ignores it.
Note, we replace the use of "extra" with "cmdline" since that is
preferred and matches the option in.
Note 2: Disks should be specified by hda, and they will be reverted to
xvda for PV domains.
=> xenmgr: Avoid generating invalid configs

dbd/dbd.ml
Add a `--pidfile` option to provide the path to a pidfile where the pid of the running daemon is saved for life-cycle control.
=> dbd: write child pidfile

xenmgr/Vm/Actions.hs, xenmgr/Vm/Config.hs, xenmgr/XenMgr/Connect/Xl.hs
xenmgr changes for using Xen 4.16.
=> xenmgr: Xen 4.16 support
